# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0004_auto_20180519_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
