# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0007_auto_20180519_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
