# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0008_auto_20180519_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='barrio',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='claseVial',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='codPostal',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='distrito',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='localidad',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='nombreVia',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='numero',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='museo',
            name='telefono',
            field=models.TextField(null=True),
        ),
    ]
