# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0012_auto_20180520_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
