# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-21 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0013_seleccion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='letra',
        ),
    ]
